name: Deploy Documentation

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel cffi xxhash pdoc

    - name: Build CFFI extension
      run: |
        python setup.py build_ext

    - name: Install package
      run: |
        python setup.py install

    - name: Generate documentation
      run: |
        pdoc pyfusefilter --output-dir docs --html --force --show-source --search --docformat google

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
